'use strict';
state.coach=FORMCOACH.normalize(state.coach);
// Apply the user's confirmed preferences once; keep their later edits and check-ins.
if(state.coach.personalization!=='strength-mobility-35-iphone-v1'){
  const previous=state.coach.profile;
  state.coach=FORMCOACH.normalize({...state.coach,personalization:'strength-mobility-35-iphone-v1',level:previous?state.coach.level:0,easyRun:0,note:'Start with a comfortable push-up variation. Your exercise history is not yet assessed; feedback will set the next step.',profile:{...(previous||{}),age:35,adult:true,device:'iphone',goal:'strength',focus:'chest-arms-core-mobility',activity:previous?.activity||'unassessed',minutes:20,days:4,health:'clear',pushVariation:previous?.pushVariation||'wall',why:'A strong, fit body, with extra attention to chest, arms, abs, and mobility.',notes:'No pain or health issues reported. Prefer four sessions per week, with three as the minimum.'}});
}
if(typeof state.autoAdvance!=='boolean')state.autoAdvance=true;

let currentReadiness={},pendingMode='full',launchFromReadiness=false;
const originalDay=getDay,originalToday=renderToday,originalPlan=renderPlan,originalProgress=renderProgress;
const originalStart=startSession,originalFinish=showFinish,originalLog=showLog,originalSettings=openSettings;
const coachDialog=document.createElement('dialog');coachDialog.id='coach-dialog';coachDialog.className='modal';coachDialog.setAttribute('aria-labelledby','coach-title');document.body.appendChild(coachDialog);
function localDay(){const d=new Date();return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function closeCoach(){coachDialog.close();coachDialog.innerHTML=''}
function coachModal(title,html){coachDialog.innerHTML=`<div class="modal-inner"><div class="modal-head"><h2 id="coach-title">${title}</h2><button type="button" class="icon-btn" data-coach-close aria-label="Close">${icon('close')}</button></div>${html}</div>`;if(!coachDialog.open)coachDialog.showModal()}
function selectField(id,label,values,value='',help=''){return `<label class="setting"><b>${label}</b><select id="${id}" required><option value="">Choose…</option>${values.map(([v,t])=>`<option value="${v}" ${String(value)===String(v)?'selected':''}>${t}</option>`).join('')}</select>${help?`<p class="small">${help}</p>`:''}</label>`}
function openProfile(){
  const p=state.coach.profile||{};
  coachModal('A plan that fits your life.',`<form id="profile-form" class="coach-form"><p class="coach-help">Choose your starting point. Your session length and weekly plan will use these answers. You can change them later.</p><label class="setting"><b>Your name</b><input id="profile-name" type="text" maxlength="40" autocomplete="given-name" value="${esc(state.name)}" placeholder="Optional"></label>${selectField('profile-goal','Your main goal',Object.entries(FORMCOACH.goals),p.goal)}${selectField('profile-activity','How active are you now?',[['unassessed','Starting level not yet assessed'],['inactive','Rarely or never exercise'],['some','About once or twice a week'],['regular','Three or more times a week']],p.activity)}<div class="pair">${selectField('profile-minutes','Total time, including warm-up and stretches',[[15,'Up to 15 minutes'],[20,'Up to 20 minutes']],p.minutes,'The main circuit is shortened to fit. Extra pauses and watching videos add time.')}${selectField('profile-days','Sessions per week',[[3,'3 strength sessions'],[4,'3 strength + 1 mobility session']],p.days)}</div>${selectField('profile-push','Push-up variation',[['wall','Wall push-up · easiest starting option'],['knees','Modified push-up · knees on the floor']],p.pushVariation,'Choose the version you can control without pain. Revisit it if every set feels easy.')}<label class="setting"><b>What will make this worth it?</b><textarea id="profile-why" maxlength="240" rows="2" placeholder="For example: feel stronger and more confident in my clothes">${esc(p.why||'')}</textarea></label><label class="setting"><b>A reliable time to start</b><input id="profile-anchor" type="text" maxlength="120" placeholder="For example: after coffee on workout mornings" value="${esc(p.anchor||'')}"><p class="small">This is a habit cue displayed in the app. It does not schedule a notification.</p></label>${selectField('profile-health','Any pain, injury, or health restriction?',[['clear','No known exercise restriction'],['guidance','I need individual exercise guidance']],p.health)}<label class="setting"><b>Anything the plan should account for?</b><textarea id="profile-notes" maxlength="400" rows="2" placeholder="Restrictions, difficult movements, or other context">${esc(p.notes||'')}</textarea><p class="small">These notes are saved for review. The app does not interpret medical information or diagnose injuries.</p></label><label class="check-label"><input id="profile-adult" type="checkbox" required ${p.adult?'checked':''}>I’m 18 or older.</label><p class="coach-help">This is a foundation plan. It adapts timing and workload from your entries; it cannot assess technique or guarantee a change in physique.</p><div id="profile-error" role="alert" class="coach-error" hidden></div><button type="submit" class="btn primary wide">Save my profile ${icon('arrow')}</button></form>`)
}
getDay=function(n){
  const p=state.coach?.profile;if(!p)return originalDay(n);
  // Keep completed days true to the workout actually logged, even if preferences change.
  const saved=state.completed[n]?.daySnapshot;if(saved&&saved.n===n&&['strength','move','rest'].includes(saved.type)&&Array.isArray(saved.ex)&&saved.ex.every(id=>EX[id]))return {...saved,w:Math.floor((n-1)/7),title:saved.type==='strength'?'Completed strength session':saved.type==='move'?'Completed movement session':'Recovery day',focus:'Your saved check-in.'};
  const type=FORMCOACH.schedule(n,p.days),w=Math.floor((n-1)/7),i=(n-1)%7;
  if(p.focus==='chest-arms-core-mobility')return personalDay(n,p,type);
  if(type==='rest')return {n,w,type,title:n===28?'Recover & review':'Rest & recharge',focus:'Take space to recover.',ex:[]};
  if(type==='move')return {n,w,type,title:'Easy movement day',focus:'Move comfortably and keep the habit.',ex:['march','step','cat','stretch']};
  const groups=[['squat','push','bridge','bird','calf'],['hinge','push','dead','side','prone'],['squat','push','bridge','prone','bird']];
  const k=p.days===2?(i===0?0:1):({0:0,2:1,4:2}[i]);
  return {n,w,type,title:['Full-body foundations','Control & core','Full-body flow'][k],focus:'A session fitted to your time and latest feedback.',ex:groups[k]};
};
function recommendation(n,mode='full'){return FORMCOACH.recommend(state.coach,currentReadiness,mode,state.pace==='gentle')}
buildSteps=function(n,mode,pace=state.pace){
  const d=getDay(n);if(d.type==='rest')return [];
  if(state.coach.profile?.focus==='chest-arms-core-mobility')return personalSteps(n,mode,pace);
  if(d.type==='move')return [{id:'march',seconds:90,phase:'Warm-up',round:0},...['step','cat','stretch','march','step','stretch'].map(id=>({id,seconds:45,phase:'Easy movement',round:0})),{id:'breath',seconds:60,phase:'Cool-down',round:0}];
  const p=FORMCOACH.recommend(state.coach,currentReadiness,mode,pace==='gentle'),steps=[];
  const add=(id,seconds,phase,round=0)=>steps.push({id,seconds,phase,round});
  add('march',p.warm/2,'Warm-up');add('circles',p.warm/4,'Warm-up');add('hinge',p.warm/4,'Warm-up');
  for(let round=1;round<=p.rounds;round++)d.ex.forEach((id,i)=>{add(id,p.work,'Work',round);if(i<4||round<p.rounds)add('rest',p.rest,'Rest',round)});
  add('breath',p.cool/2,'Cool-down');add('stretch',p.cool/2,'Cool-down');return steps;
};
function validSavedSteps(steps){return Array.isArray(steps)&&steps.length>0&&steps.length<=100&&steps.every(s=>s&&(EX[s.id]||s.id==='rest')&&Number.isFinite(s.seconds)&&s.seconds>0&&s.seconds<=180&&['Warm-up','Work','Rest','Easy movement','Cool-down'].includes(s.phase)&&Number.isInteger(s.round)&&s.round>=0&&s.round<=3)}
if(state.draft){const d=state.draft;if(!validDraft(d)||!validSavedSteps(d.steps)||d.index>=d.steps.length||d.remaining>d.steps[d.index].seconds*1000){state.draft=null;showToast('The previous session used an older plan. Your completed check-ins are kept; start a fresh session.')}}
function coachBanner(){const p=state.coach.profile;if(!p)return `<section class="coach-lead"><div><span class="label">Your personal starting point</span><h2>Let’s make this your plan.</h2><p>Set a goal, choose the time you can protect, and build from your current activity level.</p></div><button class="btn" data-coach-profile>Set up my plan ${icon('arrow')}</button></section>`;return `<section class="coach-lead"><div><span class="label">${esc(FORMCOACH.goals[p.goal])}</span><h2>${p.days===4?'3 strength + 1 mobility':p.days+' strength sessions'}. Your pace.</h2><p>${esc(state.coach.note)}${p.anchor?'<br><b>Your starting cue:</b> '+esc(p.anchor):''}</p></div><button class="btn" data-coach-profile>Edit my profile</button></section>`}
renderToday=function(){let html=originalToday();const p=state.coach.profile,d=getDay(selected),rec=recommendation(selected);html=html.replace('<div class="dashboard">',coachBanner()+'<div class="dashboard">');html=html.replace('<aside>','<aside>'+personalPlanSummary());html=html.replace(/3 strength sessions each week/,`${p?.days===4?'3 strength sessions and 1 mobility session':(p?.days||3)+' strength sessions'} each week`);if(d.type==='move'){html=html.replace(d.ex.length+' moves',d.ex.length+' mobility moves')}if(d.type==='strength'){html=html.replace(/(?:1|2|3) rounds/,`${rec.rounds} round${rec.rounds===1?'':'s'}`)}html=html.replace('A little less rest, only if you feel ready.','Readiness comes before progression.');return html};
weeks.forEach((w,i)=>{w.note=['Establish a comfortable baseline.','Use feedback from your actual sessions.','Improve control before adding workload.','Review your progress and choose the next phase.'][i]});
renderPlan=function(){const p=state.coach.profile;return personalPlanSummary()+originalPlan().replace('Three strength days a week.',`${p?.days===4?'Three strength sessions and one mobility session':(p?.days||3)+' strength sessions'} each week.`).replace('Timing includes warm-up, work, rest, and cool-down.','Previews use your current level; future sessions update after check-ins. Timing includes warm-up, work, rest, and cool-down.')};
function goalAdvice(){const p=state.coach.profile;if(!p)return 'Start by choosing a goal. Your check-ins will help you see what you can sustain.';return {strength:'Track whether the same movements feel easier at the same level. This foundation phase has limited pulling resistance; a longer-term muscle-building plan needs a fresh assessment as you progress.',leaner:'Use consistent measurements over several weeks if you find them useful. Training supports your goal, while everyday activity and eating habits also matter. This app does not prescribe calories or promise a 28-day transformation.',consistency:'Count the sessions you actually completed. If starting is still difficult, shorten the session and attach it to a routine you already do.'}[p.goal]}
function reviewHTML(){
  const p=state.coach.profile,cutoff=Date.now()-7*86400000,logs=Object.entries(state.completed).filter(([n,l])=>Date.parse(l.date)>=cutoff&&Date.parse(l.date)<=Date.now());
  const strength=logs.filter(([n,l])=>(l.daySnapshot?.type||getDay(+n).type)==='strength'&&l.mode!=='recovery'),full=strength.filter(([n,l])=>l.mode==='full').length;
  const records=state.coach.measures.slice().sort((a,b)=>b.date.localeCompare(a.date));
  return `<section class="card coach-review"><div class="row between wrap"><h3>Your last 7 days</h3><button class="text-btn" data-coach-measure>Add a measurement</button></div><div class="coach-metrics"><span><strong>${full} / ${p?.days===4?3:(p?.days||'–')}</strong>full strength sessions</span><span><strong>${strength.length-full}</strong>short or partial sessions</span><span><strong>${logs.filter(([n,l])=>(l.daySnapshot?.type||getDay(+n).type)==='move'&&l.mode==='full').length} / ${p?.days===4?1:0}</strong>mobility sessions</span></div><p>${esc(goalAdvice())}</p>${p?.why?`<div class="coach-reason"><b>Your reason for starting</b><br>${esc(p.why)}</div>`:''}<div class="coach-reason"><b>What happens next</b><br>${esc(state.coach.note)}</div><details><summary>How the plan responds to you</summary><p class="coach-help">A hard strength session reduces the starting level. Three full sessions marked easy at your current level allow one small increase. Short or partial sessions do not trigger progression. Low energy or mild soreness make today lighter. Pain or severe soreness prompts recovery. These are conservative starter rules, not a medical or technique assessment.</p></details>${records.length?`<ul class="coach-measure-list">${records.map(m=>`<li><span>${m.date} · ${measureLabel(m.kind)}<br><b>${m.value} ${measureUnit(m.kind)}</b></span><button class="text-btn" data-coach-delete-measure="${esc(m.id)}" aria-label="Remove ${m.date} ${measureLabel(m.kind)} entry">Remove</button></li>`).join('')}</ul>`:'<p class="coach-help" style="margin-top:18px">Measurements are optional. Your activity history already gives you a starting point.</p>'}</section>`;
}
renderProgress=function(){return reviewHTML()+originalProgress()};
function openReadiness(mode,resume=false){pendingMode=mode;
  coachModal('How are you today?',`<form id="readiness-form" class="coach-form" data-resume="${resume}"><p class="coach-help">A quick check-in ${resume?'before resuming your saved session':'to set today’s pace'}. ${state.autoAdvance?'Your timer advances automatically while the app is open.':'Tap Continue after each interval; automatic advancement is off in Settings.'} Review any unfamiliar movement before beginning.</p>${selectField('ready-energy','Your energy',[['normal','Enough to exercise'],['low','Low — keep it lighter']])}${selectField('ready-soreness','Muscle soreness',[['none','Little or none'],['mild','Mild, everyday movement feels normal'],['high','Enough to affect everyday movement']])}${selectField('ready-pain','Any current pain or unusual symptoms?',[['no','No'],['yes','Yes']])}<div id="readiness-error" class="coach-error" role="alert" hidden></div><button class="btn primary wide" type="submit">${resume?'Review and resume':'Prepare my session'} ${icon('arrow')}</button></form>`)
}
startSession=function(mode,resume=false){
  if(!state.coach.profile){openProfile();return}
  const base=FORMCOACH.recommend(state.coach);if(base.blocked){coachModal('Your starting point needs advice.',`<p class="coach-help">${esc(base.blocked)}</p><button class="btn primary" data-coach-profile>Review my profile</button>`);return}
  if(!launchFromReadiness){if(resume&&state.draft)selected=state.draft.day;const warning=cautionNeeded(selected);if(warning&&!resume){showToast(warning);return}openReadiness(mode,resume);return}
  originalStart(mode,resume);if(session){session.coachPlan=resume&&state.draft?.coachPlan?state.draft.coachPlan:recommendation(selected,mode);session.daySnapshot=resume&&state.draft?.daySnapshot?state.draft.daySnapshot:getDay(selected);if(session.daySnapshot.type==='move')session.coachPlan={kind:'mobility',seconds:session.steps.reduce((sum,step)=>sum+step.seconds,0)};saveDraft();}
};
showFinish=function(recovery=false){originalFinish(recovery);const save=$('#save-checkin');if(save&&!recovery){save.insertAdjacentHTML('beforebegin','<label class="check-label" style="text-align:left;margin:18px 0"><input type="checkbox" id="coach-pain">I felt pain or unusual symptoms during this session.</label><p class="small" style="margin-bottom:18px;text-align:left">Pain is different from ordinary effort. Stop the painful movement; seek help for persistent or concerning symptoms.</p>')}
};
function logFeedback(n,mode,feeling){const pain=$('#coach-pain')?.checked===true,daySnapshot=session?.daySnapshot||getDay(n),plan=session?.coachPlan||null;
  state.coach=FORMCOACH.feedback(state.coach,{type:daySnapshot.type,mode,feeling,pain,level:plan?.level,lighter:plan?.lighter===true});return {pain,daySnapshot,coachPlan:plan};
}
showLog=function(n){originalLog(n);const l=state.completed[n];if(l?.coachPlan&&l.daySnapshot?.type==='strength'){$('#detail-content').insertAdjacentHTML('beforeend',`<p class="coach-help">Session saved at level ${Number(l.coachPlan.level)+1}, ${Number(l.coachPlan.work)} seconds per work interval. ${l.pain?'Pain was reported.':''}</p>`)}
};
openSettings=function(){originalSettings();if(!$('#coach-profile-settings'))$('#settings-save').insertAdjacentHTML('beforebegin','<button class="btn outline wide coach-setup-link" id="coach-profile-settings" data-coach-profile>Edit my goal & profile</button>');$('#install-button').disabled=localPreview()||window.matchMedia('(display-mode: standalone)').matches;$('#install-message').textContent=localPreview()?'Home-screen installation becomes available after this app is published at an HTTPS address.':window.matchMedia('(display-mode: standalone)').matches?'This app is already open in standalone mode.':installPrompt?'An installation prompt is available.':'iPhone: Safari → Share → Add to Home Screen → Open as Web App (if shown) → Add. Android: browser menu → Install app. Installation depends on browser support.'};
function measureLabel(kind){return {weight:'Weight',waist:'Waist',walk:'Walking minutes'}[kind]||''}
function measureUnit(kind){return {weight:'kg',waist:'cm',walk:'min'}[kind]||''}
function openMeasure(){coachModal('Choose what to track.',`<form class="coach-form" id="measure-form"><p class="coach-help">Optional self-reported measurements. Compare like-for-like conditions and look at trends, not one reading. These entries do not change workout difficulty.</p>${selectField('measure-kind','Measurement',[['weight','Body weight (kg)'],['waist','Waist circumference (cm)'],['walk','Walking time today (minutes)']])}<label class="setting"><b>Value</b><input id="measure-value" type="number" min="0.1" max="500" step="0.1" inputmode="decimal" required></label><label class="setting"><b>Date</b><input id="measure-date" type="date" max="${localDay()}" value="${localDay()}" required></label><div class="coach-error" id="measure-error" role="alert" hidden></div><button class="btn primary wide" type="submit">Save measurement</button></form>`)}
function displayError(id,message){const e=$('#'+id);e.hidden=false;e.textContent=message}
// Forms are local. Nothing is sent to a server or a coach.
document.addEventListener('submit',e=>{
  if(e.target.id==='profile-form'){
    e.preventDefault();const profile={...(state.coach.profile||{}),goal:$('#profile-goal').value,activity:$('#profile-activity').value,minutes:Number($('#profile-minutes').value),days:Number($('#profile-days').value),health:$('#profile-health').value,adult:$('#profile-adult').checked,why:$('#profile-why').value.trim(),anchor:$('#profile-anchor').value.trim(),notes:$('#profile-notes').value.trim(),pushVariation:$('#profile-push').value};
    const old=state.coach.profile,newCoach=FORMCOACH.normalize({...state.coach,profile});if(!newCoach.profile){displayError('profile-error','Complete the required choices and adult confirmation.');return}
    if(!old||old.activity!==profile.activity||old.pushVariation!==profile.pushVariation){newCoach.level=old?.pushVariation!==profile.pushVariation||['inactive','unassessed'].includes(profile.activity)?0:1;newCoach.easyRun=0;newCoach.note='Your next sessions establish a comfortable starting point. Progression follows your feedback.';}
    state.name=$('#profile-name').value.trim().slice(0,40);state.coach=newCoach;currentReadiness={};persist();closeCoach();render();showToast('Your profile is saved. The plan will use your check-ins.');
  }
  if(e.target.id==='readiness-form'){
    e.preventDefault();const r={energy:$('#ready-energy').value,soreness:$('#ready-soreness').value,pain:$('#ready-pain').value};
    if(!r.energy||!r.soreness||!r.pain){displayError('readiness-error','Choose an answer for each check-in.');return}
    const rec=FORMCOACH.recommend(state.coach,r,pendingMode,state.pace==='gentle');if(rec.blocked){displayError('readiness-error',rec.blocked);return}
    const resume=e.target.dataset.resume==='true';
    if(resume&&(r.energy==='low'||r.soreness==='mild')){displayError('readiness-error','Your saved session keeps its original workload. Close this check-in, choose Start fresh, and use a lighter session today.');return}
    currentReadiness=r;closeCoach();launchFromReadiness=true;try{startSession(pendingMode,resume)}finally{launchFromReadiness=false}
  }
  if(e.target.id==='measure-form'){
    e.preventDefault();const kind=$('#measure-kind').value,value=Number($('#measure-value').value),date=$('#measure-date').value;
    if(!['weight','waist','walk'].includes(kind)||!Number.isFinite(value)||value<=0||value>500||!/^\d{4}-\d{2}-\d{2}$/.test(date)||date>localDay()){displayError('measure-error','Enter a valid measurement and a date no later than today.');return}
    state.coach.measures.push({id:Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7),kind,value,date});persist();closeCoach();tab='progress';render();showToast('Measurement saved.');
  }
});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.dataset.undo&&!state.completed[Number(b.dataset.undo)]){state.coach.level=['inactive','unassessed'].includes(state.coach.profile?.activity)?0:1;state.coach.easyRun=0;state.coach.note='A check-in was removed. Start again from your profile’s baseline; future feedback will rebuild progression.';persist();render()}
  if(b.hasAttribute('data-coach-profile')){if($('#settings-dialog').open)$('#settings-dialog').close();openProfile()}
  if(b.hasAttribute('data-coach-close'))closeCoach();
  if(b.hasAttribute('data-coach-measure'))openMeasure();
  if(b.hasAttribute('data-coach-delete-measure')){if(window.confirm('Remove this measurement?')){state.coach.measures=state.coach.measures.filter(m=>m.id!==b.dataset.coachDeleteMeasure);persist();render()}}
  if(b.hasAttribute('data-play-source')){const id=b.dataset.playSource,s=DEMO_SOURCES[id];if(s?.embed){if(session)pause();if(navigator.onLine===false){showToast('Videos need an internet connection. The written steps are available below.');return}const slot=$('#human-player');slot.innerHTML=`<div class="video-shell"><iframe title="${esc(EX[id].name)} demonstration by ${esc(s.provider)}" src="https://www.youtube-nocookie.com/embed/${s.embed}" allow="fullscreen; encrypted-media; picture-in-picture" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe></div>`;}}
});
coachDialog.addEventListener('close',()=>{coachDialog.innerHTML=''});
$('#detail-dialog').addEventListener('close',()=>{$('#detail-content').innerHTML=''});
persist();render();
