'use strict';
const NHS_DEMOS='https://www.nhs.uk/live-well/exercise/strength-and-flex-exercise-plan-how-to-videos/';
const NUH_DEMOS='https://www.nuh.nhs.uk/exercise-videos-spine-school/';
const DEMO_SOURCES={
  march:{provider:'NHS',url:NHS_DEMOS,type:'video',label:'Warm-up video',note:'Open the warm-up section. This is a general warm-up demonstration; follow the easy march instructions below for this interval.'},
  circles:{provider:'NHS',url:NHS_DEMOS,type:'video',label:'Warm-up video',note:'Open the warm-up section. Use the written shoulder-roll instructions below for this specific interval.'},
  hinge:{provider:'American Council on Exercise',url:'https://www.acefitness.org/resources/everyone/exercise-library/33/hip-hinge/',type:'guide',label:'Hip hinge technique guide',note:'This source is a technique guide. A matched filmed demonstration is still to be added.'},
  ankle:{provider:'NHS inform',url:'https://www.nhsinform.scot/illnesses-and-conditions/muscle-bone-and-joints/leg-and-foot-problems-and-conditions/exercises-for-calf-and-ankle-problems/',type:'guide',label:'Ankle movement reference',note:'This is a related exercise library. Follow the ankle-rock instructions below; it is not a matched video for this move.'},
  squat:{provider:'NHS',url:NHS_DEMOS,type:'video',label:'Squat demonstration',note:'On the NHS page, choose “NHS Strength and flexibility – squat”.'},
  push:{provider:'NHS',url:NHS_DEMOS,type:'video',label:'Standing press-up demonstration',note:'On the NHS page, choose “standing press-up”. Use a solid wall for the version in this plan.'},
  bridge:{provider:'Nottingham University Hospitals NHS Trust',url:NUH_DEMOS,embed:'iZ611vwxI4I',type:'video',label:'Bridge demonstration',note:'The hospital page also contains rehabilitation exercises. Use this clip for movement technique, not as an injury-treatment plan.'},
  bird:{provider:'American Council on Exercise',url:'https://www.acefitness.org/resources/everyone/exercise-library/14/bird-dog/',type:'guide',label:'Bird dog technique guide',note:'This source is a technique guide. Start with one limb at a time if needed; a matched filmed demonstration is still to be added.'},
  calf:{provider:'NHS inform',url:'https://www.nhsinform.scot/illnesses-and-conditions/muscle-bone-and-joints/leg-and-foot-problems-and-conditions/exercises-for-calf-and-ankle-problems/',type:'video',label:'Heel-raise video library',note:'Select the heel-raise movement. Use the wall for balance and follow the easier option if needed.'},
  dead:{provider:'Nottingham University Hospitals NHS Trust',url:NUH_DEMOS,type:'video',label:'Heel-slide demonstration',note:'Select “Trans Abdominal Heel Slide”, with the heel supported on the floor. Do not select the unsupported variation.'},
  side:{provider:'South Tees Hospitals NHS Foundation Trust',url:'https://www.southtees.nhs.uk/resources/hip-abduction-in-standing/',type:'video',label:'Standing hip abduction',note:'Open the video linked on the provider’s page. Use support and keep your trunk still.'},
  prone:{provider:'South Tees Hospitals NHS Foundation Trust',url:'https://www.southtees.nhs.uk/resources/shoulder-posture/',type:'guide',label:'Shoulder position guide',note:'A standing shoulder-blade exercise replaces the earlier prone animation. Follow the written version below.'},
  step:{provider:'NHS',url:NHS_DEMOS,type:'video',label:'Warm-up overview',note:'This video is a general warm-up reference. The side-step-and-reach interval is explained below; a matched filmed clip is still to be added.'},
  cat:{provider:'American Council on Exercise',url:'https://www.acefitness.org/resources/everyone/exercise-library/15/cat-cow/',type:'guide',label:'Cat–cow technique guide',note:'This source is a technique guide. A matched filmed demonstration is still to be added.'},
  breath:{provider:'NHS',url:'https://www.nhs.uk/mental-health/self-help/guides-tools-and-activities/breathing-exercises-for-stress/',type:'guide',label:'Breathing reference',note:'For this cool-down, let your breath settle naturally. No forced deep breaths or breath-holding.'},
  stretch:{provider:'NHS',url:NHS_DEMOS,type:'video',label:'Upper-back stretch demonstration',note:'Choose the upper-back stretch section on the NHS page. Use a comfortable range.'}
};
EX.prone={name:'Standing shoulder-blade squeeze',area:'Upper back · shoulder control',cue:'Draw your shoulder blades gently toward each other, then relax. Keep breathing.',steps:['Stand comfortably, keep your upper arms close to your sides, and bend your elbows comfortably.','Gently move your shoulder blades toward each other without shrugging or arching your lower back.','Hold briefly, then relax. Keep the movement small and comfortable.'],easy:'Use less movement and less effort. Stop if it causes pain.',pose:'stand'};
EX.stretch={name:'Gentle upper-back stretch',area:'Cool-down · upper back',cue:'Reach your arms gently in front of you and let your upper back soften. Do not force the stretch.',steps:['Stand comfortably with your feet supported and knees soft.','Bring your hands together in front and gently reach them away from your chest.','Feel a mild stretch across your upper back, breathe normally, then release.'],easy:'Keep your elbows slightly bent and reduce how far you reach.',pose:'stand'};
function sourcePanel(id,compact=false){const s=DEMO_SOURCES[id];return `<div class="source-panel"><span class="label">${s.type==='video'?'Human demonstration resource':'Written technique resource'}</span><h3>${esc(s.label)}</h3>${!compact?`<p>${esc(s.note)}</p>`:''}${s.embed&&!compact?`<button class="btn primary" data-play-source="${id}">${icon('play')} Play demonstration</button><div id="human-player"></div>`:''}<a class="btn ${s.embed&&!compact?'outline':'primary'}" href="${s.url}" target="_blank" rel="noopener noreferrer">Open ${esc(s.provider)} ↗</a>${!compact?'<p class="small">Requires internet. External providers host their own content; these links do not mean they endorse this app.</p>':''}</div>`}
demoVideo=function(id,controls=true){return sourcePanel(id,!controls)};
detail=function(id){if(session)pause();const e=EX[id];$('#detail-content').innerHTML=`<div class="modal-head"><h2 id="detail-title">${e.name}</h2><button class="icon-btn" data-close="detail-dialog" aria-label="Close exercise instructions">${icon('close')}</button></div>${sourcePanel(id)}<p class="label muted">${e.area}</p><ol class="steps">${e.steps.map(s=>'<li>'+s+'</li>').join('')}</ol><div class="easier"><b>Make it easier</b><br>${e.easy}</div><p class="small">Stay within a comfortable range. Stop before your form breaks down.</p>`;$('#detail-dialog').showModal()};
