'use strict';
// Provider pages and sampled playback reviewed on 2026-09-16. The full set is not verified; see validation/.
// No third-party media is bundled.
const PLANNED_EXERCISES=['march','circles','hinge','side','push','kneepush','squat','bridge','bird','dead','plankknees','prone','calf','cat','cheststretch','stretch','calfhold','breath'];
const southTees='South Tees Hospitals NHS Foundation Trust';
const hingeVideo=(path,label,note)=>({provider:'Hinge Health',url:'https://www.hingehealth.com/resources/articles/'+path+'/',type:'video',label,note,checked:'2026-09-16'});
Object.assign(DEMO_SOURCES,{
  march:{provider:'NHS',url:'https://www.nhs.uk/live-well/exercise/how-to-warm-up-before-exercising/',type:'video',label:'Basic warm-up video',note:'Use the march-on-the-spot movement. This is a warm-up tutorial covering several movements; the app times your marching interval separately.'},
  circles:{provider:'NHS',url:'https://www.nhs.uk/live-well/exercise/how-to-warm-up-before-exercising/',type:'video',label:'Basic warm-up video',note:'Use the shoulder-roll movement. Keep your arms relaxed; the app sets the interval for this movement.'},
  hinge:hingeVideo('hip-hinge','Hip hinge tutorial','Watch the standard hip hinge in the exercise section. Use a small range during preparation; no weights are needed.'),
  cat:hingeVideo('cat-cow','Cat–cow tutorial','Watch the standard hands-and-knees version. Move gently through a comfortable range.'),
  calf:hingeVideo('calf-raises','Calf raise tutorial','Use the basic two-leg version on the floor, with a wall for balance. Skip the step and single-leg progressions.'),
  plankknees:hingeVideo('plank-on-knees','Plank on knees tutorial','Watch the knees-supported version on forearms. Use short 10–15 second holds, resting as needed inside the interval.'),
  push:{provider:southTees,url:'https://www.southtees.nhs.uk/resources/combined-press-ups/',embed:'kmzcmFZ9NyY',type:'video',label:'Wall push-up tutorial',note:'Use the wall version. Stand closer to the wall for an easier starting point.'},
  kneepush:{provider:southTees,url:'https://www.southtees.nhs.uk/resources/combined-press-ups/',embed:'LD9qrH7o2fY',type:'video',label:'Knee push-up tutorial',note:'Keep your knees supported and work through a range you can control. The wall version is available as an easier option.'},
  prone:{provider:southTees,url:'https://www.southtees.nhs.uk/resources/shoulder-posture/',embed:'hNseglwRJhY',type:'video',label:'Shoulder-blade control tutorial',note:'Gently bring the shoulder blades toward each other, pause briefly and relax. Avoid shrugging or arching your back.'},
  bird:{provider:'Hospital for Special Surgery',url:'https://www.youtube.com/watch?v=xo7Qpb_NTKE',embed:'xo7Qpb_NTKE',type:'video',label:'Bird-dog tutorial',note:'Learn the opposite-arm-and-leg movement. Start with a smaller reach or one limb at a time if needed.'},
  dead:{provider:'Nottingham University Hospitals NHS Trust',url:'https://www.nuh.nhs.uk/exercise-videos-spine-school/',embed:'t2sYmCjr7Hs',type:'video',label:'Supported heel-slide tutorial',note:'Keep the sliding heel supported on the floor. Use this supported version, not the unsupported progression.'},
  breath:{provider:'The Royal Marsden NHS Foundation Trust',url:'https://patientinfolibrary.royalmarsden.nhs.uk/royal-mile-prehabilitation-programme-video-7c-diaphragmatic-breathing',type:'video',label:'Relaxed diaphragmatic breathing · Video 7c',note:'Open Video 7c. This clinician-led explanation combines a presenter with breathing diagrams; it is not a full-body demonstration. For your cool-down, breathe gently without forcing deep breaths or holding your breath. The written steps below remain available offline.'}
});
EX.breath={name:'Relaxed belly breathing',area:'Cool-down · recovery',cue:'Let your breath settle. Keep the breaths gentle and unforced.',steps:['Lie comfortably with knees bent, or sit in a comfortable position. Rest a hand lightly on your belly.','Breathe in gently and notice a small movement under your hand, then breathe out slowly.','Keep breathing naturally without holding your breath. Rest normally if this feels uncomfortable.'],easy:'Skip the hand placement and simply let your breathing return to normal.',pose:'stand'};
for(const id of PLANNED_EXERCISES){DEMO_SOURCES[id].checked='2026-09-16';DEMO_SOURCES[id].playbackVerified=false;}
sourcePanel=function(id,compact=false){
  const s=DEMO_SOURCES[id];
  if(!s||s.type!=='video')return `<div class="source-panel"><span class="label">Saved exercise</span><p>Use the written steps below. This movement is from an earlier version of the plan.</p></div>`;
  if(compact)return `<div class="source-panel compact-demo"><div><span class="label">Video guidance</span><h3>${esc(s.label)}</h3><p>${esc(s.provider)}</p></div><button class="btn outline" type="button" data-exercise="${id}">${icon('play')} Learn this move</button></div>`;
  const videoURL=s.embed?'https://www.youtube.com/watch?v='+s.embed:s.url;
  return `<div class="source-panel"><span class="label">Video guidance · ${esc(s.provider)}</span><h3>${esc(s.label)}</h3><p>${esc(s.note)}</p>${s.embed?`<button class="btn primary" data-play-source="${id}">${icon('play')} Play demonstration</button><div id="human-player"></div>`:''}<a class="btn ${s.embed?'outline':'primary'}" href="${videoURL}" data-demo-link target="_blank" rel="noopener noreferrer">${s.embed?'Open video on YouTube':'Watch on '+esc(s.provider)} ↗</a><p class="small">${s.embed?'If the player is unavailable, use the direct video link or provider page.':'The video opens on the provider’s page; go to the named exercise section.'} Internet required. Your workout stays paused while you learn.</p>${s.embed && !s.url.includes('youtube.com') ? `<a href="${s.url}" target="_blank" rel="noopener noreferrer">Provider page and written reference ↗</a>` : ''}</div>`;
};
renderMoves=function(){return `<div class="intro"><div><div class="label">Learn before you begin</div><h1>Your movement library.</h1></div></div><p class="plan-desc">${PLANNED_EXERCISES.length} movements for your plan, each with video guidance, written steps and an easier option. Some videos open on the provider’s website. Warm-up videos cover several movements.</p><div class="moves-grid">${PLANNED_EXERCISES.map(id=>`<button class="move-card" data-exercise="${id}"><div class="move-art">${pose(id)}</div><span class="video-label">${icon('play')} Video guide</span><h3>${esc(EX[id].name)}</h3><p class="small">${esc(EX[id].area)}</p></button>`).join('')}</div>`};
document.addEventListener('click',event=>{if(event.target.closest('a[data-demo-link]')&&session)pause()});
