'use strict';
const assert=require('node:assert/strict');
module.exports=async function(page,checks){
  assert.equal(await page.evaluate(()=>session.paused),true);
  assert.equal(await page.locator('#workout-pace').inputValue(),'1.25');
  const plan=await page.evaluate(()=>JSON.stringify(session.steps));
  await page.locator('#workout-pace').selectOption('1');
  assert.equal(await page.evaluate(()=>state.experience.demoPace),1);
  assert.equal(await page.evaluate(()=>JSON.stringify(session.steps)),plan);
  await page.locator('#workout-pace').selectOption('1.25');
  assert.equal(await page.evaluate(()=>demoRate('breath')),1);
  assert.equal(await page.evaluate(()=>demoRate('plankknees')),1);
  await page.locator('#player-instructions summary').click();
  const remaining=await page.evaluate(()=>session.remaining);
  await page.locator('#workout-explain').click();
  const spoken=await page.evaluate(()=>window.voiceTest.at(-1).text);
  assert(spoken.includes(await page.evaluate(()=>EX[session.steps[session.index].id].steps[1])));
  assert(spoken.includes('Easier option.'));
  await page.waitForTimeout(300);
  assert.equal(await page.evaluate(()=>session.remaining),remaining);
  assert.equal(await page.evaluate(()=>coachingScope),'lesson');
  await page.locator('#workout-explain').click();
  assert.equal(await page.evaluate(()=>coachingActive),false);
  await page.locator('#player-instructions summary').click();
  // Real Web Audio graph. Speech alone uses a controlled stub in browser.cjs.
  await page.locator('#music-toggle').click();
  await page.waitForFunction(()=>beatContext?.state==='running');
  assert.equal(await page.evaluate(()=>musicRunning()),false,'No music while the workout is paused');
  await page.evaluate(()=>{
    window.beatAnalyser=beatContext.createAnalyser();beatAnalyser.fftSize=256;
    const sink=beatContext.createGain();sink.gain.value=0;beatGain.connect(beatAnalyser);beatAnalyser.connect(sink);sink.connect(beatContext.destination);
  });
  await page.locator('#timer-toggle').click();
  await page.waitForFunction(()=>{const samples=new Float32Array(256);beatAnalyser.getFloatTimeDomainData(samples);return musicRunning()&&samples.some(x=>Math.abs(x)>.0001)});
  await page.locator('#music-volume').focus();await page.keyboard.press('Home');await page.keyboard.press('ArrowRight');
  assert(Math.abs(await page.evaluate(()=>state.experience.musicVolume)-.10)<.0001);
  await page.waitForTimeout(600);
  const normalLevel=await page.evaluate(()=>beatGain.gain.value);
  await page.locator('#voice-toggle').click();
  await page.waitForTimeout(600);
  assert(await page.evaluate(()=>beatGain.gain.value)<normalLevel*.5,'Music must duck under coaching');
  await page.evaluate(()=>window.voiceTest.filter(e=>e.event==='speak').at(-1).utterance.onend());
  await page.waitForTimeout(600);
  assert(await page.evaluate(()=>beatGain.gain.value)>normalLevel*.8,'Music returns after the spoken cue');
  await page.evaluate(()=>window.dispatchEvent(new Event('pagehide')));
  assert.equal(await page.evaluate(()=>session.paused),true);
  assert.equal(await page.evaluate(()=>musicRunning()),false);
  assert.equal(await page.evaluate(()=>beatNodes.size),0);
  await page.locator('#voice-toggle').click(); // voice off
  await page.locator('#timer-toggle').click();
  await page.waitForFunction(()=>musicRunning());
  await page.locator('#music-toggle').click();
  assert.equal(await page.evaluate(()=>musicRunning()),false);
  assert.equal(await page.evaluate(()=>beatNodes.size),0);
  await page.locator('#timer-toggle').click();
  assert.equal(await page.evaluate(()=>session.paused),true);
  assert.equal(await page.evaluate(()=>JSON.stringify(session.steps)),plan);
  checks.push('Brisk/original preference, fixed workout plan, original-speed holds; complete spoken technique with paused timer (speech stub); real Web Audio signal, volume, ducking, resume and pagehide/mute cleanup');
};
